### ISSUE TITLE
[feat.] 希望增加调整水印透明度的选项

### ISSUE THREAD

**Issue by mjysci** [pdmaker/watermark-master#2]
通过滑块调整。

**Comment by pdmaker** [comment]
好的，谢谢反馈。 我目前对水印透明度的考量是通过 颜色 的深浅替代了。但的确，因为目前是没有透明度这个的（水印文字的遮挡）。

计划：1）默认直接加上一定的透明度：比如 80% 。
2）开放控制，滑块控制的方向也是我迭代的考虑；—— 这里得布局调整下。

**Comment by pdmaker** [comment]
我还是增加了透明度的控制，默认 80%的，调节方式暂时还是用的输入框。 滑块模式有利有弊，比如不利于精准控制，虽然可以操作更简单。——滑块模式的调节，我用于后续开发。 @mjysci

**Comment by mjysci** [comment]
多谢！有这个功能就行了。
