### ISSUE TITLE
本地使用直接打开index.html会出现 跨源资源共享问题

### ISSUE THREAD

**Issue by 6Hdream** [pdmaker/watermark-master#5]
问题: 克隆项目到本地，直接打开index.html，JS脚本会加载失败，只有静态页面，图片无法上传。

解决办法：使用服务器运行index.html
1. Node.js: 使用 http-server 
`npm install -g http-server`
`http-server 项目路径`
2. VS Code: 使用 Live Server 插件。
推荐使用第二种

希望在README中修改一下

**Comment by pdmaker** [comment]
好叻，已经解决了哈，目前支持 Node 和 Python 两种启动本地服务器的方式进行预览。感谢反馈

**Comment by xiaobocser** [comment]
解决问题，作者的这个工作很有价值～
